name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Execute Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm run test

  e2e-tests:
    name: Execute End-to-End Tests
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Set Up Database
        run: |
          echo "Setting up database..."
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
          cat .env
          npx prisma migrate deploy

      - name: Compile Next.js App
        run: npm run build

      - name: Start Next.js Server
        run: npm run start &
        env:
          NODE_ENV: test

      - name: Wait for Next.js Server to Start
        run: |
          echo "Waiting for Next.js to start..."
          for i in {1..30}; do
            curl -sSf http://localhost:3000/api/todos && break
            echo "Still waiting..."
            sleep 2
          done
        timeout-minutes: 2

      - name: Run Playwright Tests
        run: E2E_TEST=true npm run test:e2e

      - name: Upload Playwright Test Results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: test-results/