name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm run test

  e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build Next.js App
        run: npm run build

      - name: Start Next.js Server
        run: npm run start &
        env:
          NODE_ENV: test

      - name: Wait for Next.js to be Ready
        run: |
          for i in {1..30}; do
            curl -sSf http://localhost:3000 && break
            echo "Waiting for Next.js to start..."
            sleep 2
          done

      - name: Run Playwright E2E Tests
        run: npm run test:e2e

