name: Continuous Integrationss

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Execute Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm run test

  e2e-tests:
    name: Execute End-to-End Tests
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Compile Next.js App
        run: npm run build

      - name: Launch Next.js Server
        run: npm run start &
        env:
          NODE_ENV: test
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      
      - name: Wait Until Next.js is Ready
        run: |
          for i in {1..30}; do
            curl -sSf http://localhost:3000 > /dev/null && echo "Next.js is running!" && break
            echo "Waiting for Next.js to start..."
            sleep 2
          done
      
        
      - name: Verify API is Reachable
        run: curl -v http://localhost:3000/api/todos

      - name: Execute Playwright Tests
        run: E2E_TEST=true npm run test:e2e  
